import type { Metadata } from "next";
import AppBar from "@/components/AppBar";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
      <AppBar
        title={"My Blog"}
      />
        {children}
      </body>
    </html>
  );
}
